### ISSUE TITLE
Release 8.0.0 issue with windows defender.

### ISSUE THREAD

**Issue by Sanchelioss** [magicbear/palworld-server-toolkit#80]
Good afternoon, when downloading release 8.0.0 Windows Defender blocks the file and warns that there is a Trojan program inside.

**Comment by Sanchelioss** [comment]
And 7.9...
Previous versions did not contain this trojan Wacatac.B!ml. They loaded without any problems.

**Comment by supernet2ec** [comment]
Yeah noticed the same thing, even webroot, bitdefender, microsofts anti virus, googles anti virus, nortons antivirus have flagged versions 7.9.x up to version 8.1.x with this malicious virus. Dude why, i run my stuff in VM containers thankfully but why would you do this? Is it because your chinese devs?
